/**
 * 材料入库管理：四种入库类型 Tab：
 *  1) 采购入库：source = contract/retail，合同选择时带出甲乙双方；可定项入库（关联项目）；可选择材料 or 上传表格导入
 *  2) 退料入库：两个来源（主动发起选领料单；或领料单联动自动生成）
 *  3) 调拨入库：两个来源（主动发起选调拨单，选对方出库单数据；或调拨单联动自动生成）
 *  4) 其他入库
 * 审核入库单后，库存增加。
 */

import React, { useMemo, useState } from 'react';
import type { Project, Contract } from '@/types';
import type { StockInOrder, StockInType, DocLineItem, Material } from './types';
import {
  C, Modal, SearchBar, Input, Select, StatusPill, TypePill,
  MaterialPicker, DocLineEditor, materialsToLines, useToast, ImportLinesModal,
} from './_shared';
import {
  getStockInOrders, upsertStockIn, auditStockIn, nextDocCode, todayStr, nowStr,
  genId, getOrgsForDropdown, getWarehousesByOrg,
  STOCK_IN_STATUS_MAP, STOCK_IN_TYPE_MAP,
  patchStockInWithContract, patchStockInWithProject,
  parseImportedRows, manualReturnFromIssue, manualTransferIn,
  getIssueOrders, getTransferOrders,
} from './materialStore';

interface Props {
  key?: string | number;
  contracts: Contract[];
  projects: Project[];
  onRefresh?: () => void;
  /** 固定入库类型（从三级菜单进入时锁定，隐藏 Tab 栏） */
  fixedType?: StockInType;
}

const TABS: { key: StockInType; label: string; tone: 'cyan' | 'emerald' | 'amber' | 'slate'; icon: string }[] = [
  { key: 'purchase', label: '采购入库', tone: 'cyan', icon: 'M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z' },
  { key: 'return',   label: '退料入库', tone: 'emerald', icon: 'M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6' },
  { key: 'transfer', label: '调拨入库', tone: 'amber', icon: 'M8 7h12m0 0l-4-4m4 4l-4 4m0 6H4m0 0l4 4m-4-4l4-4' },
  { key: 'other',    label: '其他入库', tone: 'slate', icon: 'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z' },
];

export default function StockInManager({ contracts, projects, onRefresh, fixedType }: Props) {
  const [tab, setTab] = useState<StockInType>(fixedType || 'purchase');
  const [list, setList] = useState<StockInOrder[]>(() => getStockInOrders());
  const refresh = () => { setList(getStockInOrders()); onRefresh?.(); };
  const toast = useToast();
  const orgs = useMemo(() => getOrgsForDropdown().filter(o => o.level === 'project'), []);
  const [kw, setKw] = useState('');
  const [st, setSt] = useState('');

  const [open, setOpen] = useState(false);
  const [edit, setEdit] = useState<StockInOrder | null>(null);
  const [pickOpen, setPickOpen] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [viewId, setViewId] = useState<string | null>(null);

  const filtered = useMemo(() => {
    let r = list.filter(o => o.type === tab);
    if (st) r = r.filter(o => o.status === st);
    if (kw.trim()) {
      const k = kw.trim().toLowerCase();
      r = r.filter(o =>
        o.code.toLowerCase().includes(k) ||
        (o.contractName || '').toLowerCase().includes(k) ||
        (o.projectName || '').toLowerCase().includes(k) ||
        (o.supplier || '').toLowerCase().includes(k)
      );
    }
    return r.sort((a, b) => (b.createdAt || '').localeCompare(a.createdAt || ''));
  }, [list, tab, st, kw]);

  const openNew = () => {
    const doc: StockInOrder = {
      id: genId('si'),
      code: nextDocCode(
        tab === 'purchase' ? 'RK-CG-' :
        tab === 'return'   ? 'RK-TL-' :
        tab === 'transfer' ? 'RK-DB-' :
                             'RK-QT-'
      ),
      type: tab,
      orgId: '', orgName: '',
      docDate: todayStr(),
      status: 'draft',
      lines: [],
      createdAt: nowStr(), updatedAt: nowStr(),
      autoGenerated: false, sourceModule: 'stock',
    };
    if (tab === 'purchase') doc.purchaseSource = 'contract';
    setEdit(doc); setOpen(true);
  };

  const setField = <K extends keyof StockInOrder>(k: K, v: StockInOrder[K]) =>
    setEdit(e => e ? { ...e, [k]: v } as StockInOrder : e);

  const setLines = (lines: DocLineItem[]) => setEdit(e => e ? { ...e, lines } : e);

  const onPickMats = (mats: Material[]) => {
    if (!edit) return;
    const exist = new Set(edit.lines.map(l => l.materialId));
    setLines([...edit.lines, ...materialsToLines(mats.filter(m => !exist.has(m.id)))]);
  };

  const onImportRows = (rows: { code: string; name: string; quantity: number; unitPrice: number; remark?: string }[]) => {
    if (!edit) return;
    const res = parseImportedRows(rows);
    if (!res.ok) return toast('导入错误：\n' + res.errors.slice(0, 3).join('\n'), 'error');
    // 合并已有行
    const existIds = new Set(edit.lines.map(l => l.materialId));
    const add = res.lines.filter(l => !existIds.has(l.materialId));
    setLines([...edit.lines, ...add]);
    toast(`导入成功 ${add.length} 行`, 'success');
    setImportOpen(false);
  };

  const onSourceChanged = (src: 'contract' | 'retail') => {
    if (!edit) return;
    if (src === 'contract') {
      const c = contracts.find(c => c.id === edit.contractId);
      setEdit(patchStockInWithContract(edit!, c, 'contract'));
    } else {
      setEdit(patchStockInWithContract(edit!, undefined, 'retail'));
    }
  };
  const onContractChanged = (cid: string) => {
    if (!edit) return;
    const c = contracts.find(c => c.id === cid);
    setEdit(patchStockInWithContract(edit, c, edit.purchaseSource || 'contract'));
  };
  const onProjectChanged = (pid: string) => {
    if (!edit) return;
    const p = projects.find(pp => pp.id === pid);
    setEdit(patchStockInWithProject(edit, p));
    // 项目有org时联动设置org
    if (p?.org) {
      const o = orgs.find(o => o.id === p.org);
      setEdit({ ...edit, projectId: p.id, projectName: p.name, orgId: p.org, orgName: o?.name || '' });
    }
  };
  const onOrgChanged = (oid: string) => {
    if (!edit) return;
    const o = orgs.find(o => o.id === oid);
    setField('orgId', oid); setField('orgName', o?.name || ''); setField('warehouseId', undefined);
  };

  const validBeforeSave = (): boolean => {
    if (!edit) return false;
    if (!edit.orgId) { toast('请选择入库组织', 'error'); return false; }
    if (!edit.warehouseId) { toast('请选择入库仓库', 'error'); return false; }
    if (edit.lines.length === 0) { toast('请添加明细或导入入库材料表格', 'error'); return false; }
    if (tab === 'purchase') {
      if (edit.purchaseSource === 'contract' && !edit.contractId) { toast('选择了合同来源，需选择材料合同', 'error'); return false; }
    }
    if (tab === 'return' && !edit.issueOrderId) { toast('退料入库需要选择关联领料单', 'error'); return false; }
    if (tab === 'transfer' && !edit.transferOrderId) { toast('调拨入库需要选择关联调拨单', 'error'); return false; }
    return true;
  };

  const saveEditing = (audit: boolean) => {
    if (!edit) return;
    if (!validBeforeSave()) return;
    const saved = upsertStockIn({ ...edit, status: audit ? 'submitted' : 'draft' });
    if (audit) auditStockIn(saved.id);
    toast(audit ? '已审核入库，库存已更新' : '已保存草稿', 'success');
    setOpen(false); setEdit(null); refresh();
  };

  // 退料：选择领料单 → 自动带出已发材料数量
  const bindIssueOrder = (issueId: string) => {
    if (!edit) return;
    const issue = getIssueOrders().find(i => i.id === issueId);
    if (!issue) return;
    // 默认退回全部已发未退数量
    const lines: DocLineItem[] = issue.lines
      .filter(l => l.issuedQty - l.returnedQty > 0)
      .map(l => ({
        id: genId('li'),
        materialId: l.materialId, materialCode: l.materialCode, materialName: l.materialName,
        spec: l.spec, unit: l.unit,
        quantity: l.issuedQty - l.returnedQty,
        unitPrice: l.unitPrice || 0,
        sourceLineId: l.id,
      }));
    const d: StockInOrder = {
      ...edit,
      orgId: issue.orgId, orgName: issue.orgName,
      projectId: issue.projectId, projectName: issue.projectName,
      issueOrderId: issue.id, issueOrderCode: issue.code,
      lines,
    };
    setEdit(d);
    toast(`已关联领料单 ${issue.code}，共带出可退 ${lines.length} 项`, 'success');
  };

  // 调拨：选择调拨单 → 自动带出对方出库行
  const bindTransferOrder = (toid: string) => {
    if (!edit) return;
    const t = getTransferOrders().find(x => x.id === toid);
    if (!t) return;
    if (t.status !== 'out_done' && t.status !== 'completed') {
      toast('当前调拨单尚未调出，请先完成调出方出库', 'error'); return;
    }
    const lines: DocLineItem[] = t.lines.map(l => ({ ...l, id: genId('li') }));
    setEdit({
      ...edit,
      orgId: t.toOrgId, orgName: t.toOrgName,
      transferOrderId: t.id, transferOrderCode: t.code,
      fromOrgId: t.fromOrgId, fromOrgName: t.fromOrgName,
      transferOutId: t.outOrderId,
      lines,
    });
    toast(`已关联调拨单 ${t.code}，共 ${lines.length} 项`, 'success');
  };

  const warehouses = edit?.orgId ? getWarehousesByOrg(edit.orgId) : [];

  const current = viewId ? list.find(l => l.id === viewId) : null;

  return (
    <div className="p-5">
      {/* Tabs（fixedType 模式下隐藏） */}
      {!fixedType && (
      <div className="flex items-center gap-2 mb-4">
        {TABS.map(t => {
          const count = list.filter(o => o.type === t.key).length;
          const active = tab === t.key;
          return (
            <button key={t.key}
              onClick={() => setTab(t.key)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm font-medium transition-all ${
                active
                  ? 'bg-white border-cyan-400 text-cyan-700 shadow-sm ring-2 ring-cyan-100'
                  : 'bg-white/50 border-slate-200 text-slate-600 hover:bg-white hover:border-slate-300'
              }`}>
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d={t.icon} />
              </svg>
              {t.label}
              <span className={`px-1.5 py-0.5 rounded-md text-[11px] ${active ? 'bg-cyan-100 text-cyan-700' : 'bg-slate-100 text-slate-500'}`}>
                {count}
              </span>
            </button>
          );
        })}
      </div>
      )}

      <SearchBar onAdd={openNew} addLabel={`+ 新建${STOCK_IN_TYPE_MAP[tab]}`}>
        <Input value={kw} onChange={setKw} placeholder={`搜索${STOCK_IN_TYPE_MAP[tab]}单号/合同/项目/供应商`} className="!w-72" />
        <Select value={st} onChange={setSt}
          options={Object.keys(STOCK_IN_STATUS_MAP).map(k => ({ value: k, label: STOCK_IN_STATUS_MAP[k] }))}
          placeholder="状态" className="!w-40" />
        <button className={C.button.ghost} onClick={refresh}>刷新</button>
      </SearchBar>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        <table className={C.table}>
          <thead>
            <tr>
              <th className={C.th}>单据编号</th>
              <th className={C.th}>入库组织</th>
              <th className={C.th}>类型</th>
              {tab === 'purchase' && <th className={C.th}>采购来源 / 合同</th>}
              {tab === 'purchase' && <th className={C.th}>供应商</th>}
              {(tab === 'purchase' || tab === 'return') && <th className={C.th}>定项(项目)</th>}
              {tab === 'return' && <th className={C.th}>关联领料单</th>}
              {tab === 'transfer' && <th className={C.th}>调出→调入</th>}
              {tab === 'transfer' && <th className={C.th}>关联调拨单</th>}
              <th className={`${C.th} text-right`}>金额(含税)</th>
              <th className={C.th}>日期</th>
              <th className={C.th}>状态</th>
              <th className={C.th}>操作</th>
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 && (
              <tr><td colSpan={12} className={`${C.td} text-center text-slate-400 py-10`}>
                暂无{STOCK_IN_TYPE_MAP[tab]}单
                {tab !== 'other' && <div className="text-[11px] text-slate-400 mt-1">说明：主动创建 / 从调拨单/领料单联动自动生成的单据都将显示在此处</div>}
              </td></tr>
            )}
            {filtered.map(o => (
              <tr key={o.id} className="hover:bg-slate-50">
                <td className={`${C.td} font-medium`}>
                  {o.code}
                  {o.autoGenerated && <span className="ml-1 text-[10px] text-slate-400">（自动）</span>}
                </td>
                <td className={C.td}>{o.orgName}</td>
                <td className={C.td}><TypePill text={STOCK_IN_TYPE_MAP[o.type]} tone={TABS.find(t => t.key === o.type)?.tone} /></td>
                {tab === 'purchase' && (
                  <td className={C.td}>
                    {o.purchaseSource === 'contract' ? (
                      <>
                        <TypePill text="材料合同" tone="cyan" />
                        <div className="text-xs text-slate-600 mt-1">{o.contractName || '-'}</div>
                        <div className="text-[11px] text-slate-400">{o.contractCode}</div>
                      </>
                    ) : <TypePill text="零星采购" tone="slate" />}
                  </td>
                )}
                {tab === 'purchase' && (
                  <td className={C.td}>
                    <div>{o.supplier || '-'}</div>
                    {o.buyer && <div className="text-[11px] text-slate-400 mt-0.5">甲方: {o.buyer}</div>}
                  </td>
                )}
                {(tab === 'purchase' || tab === 'return') && (
                  <td className={C.td}>{o.projectName ? <span className="text-slate-800 font-medium">{o.projectName}</span> : <span className="text-slate-400">-</span>}</td>
                )}
                {tab === 'return' && <td className={C.td}>{o.issueOrderCode || '-'}</td>}
                {tab === 'transfer' && (
                  <td className={C.td}>
                    <span className="text-slate-500">{o.fromOrgName}</span>
                    <span className="mx-1 text-slate-300">→</span>
                    <span className="text-cyan-700 font-medium">{o.orgName}</span>
                  </td>
                )}
                {tab === 'transfer' && <td className={C.td}>{o.transferOrderCode || '-'}</td>}
                <td className={`${C.td} text-right tabular-nums text-cyan-700 font-medium`}>¥ {(o.totalAmount || 0).toFixed(2)}</td>
                <td className={C.td}>{o.docDate}</td>
                <td className={C.td}><StatusPill status={STOCK_IN_STATUS_MAP[o.status]} /></td>
                <td className={`${C.td} whitespace-nowrap space-x-1`}>
                  <button className={C.button.tiny} onClick={() => setViewId(o.id)}>查看</button>
                  {o.status === 'draft' && !o.autoGenerated && (
                    <button className={C.button.tiny + ' text-cyan-700 border-cyan-300'}
                      onClick={() => { setEdit(o); setOpen(true); }}>编辑</button>
                  )}
                  {o.status === 'draft' && (
                    <button className={C.button.tiny + ' text-emerald-700 border-emerald-300'}
                      onClick={() => { auditStockIn(o.id); refresh(); toast('已审核入库，库存已更新', 'success'); }}>审核入库</button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* 新建/编辑 */}
      <Modal
        title={`${STOCK_IN_TYPE_MAP[tab]} - ${edit?.code || ''}`}
        open={open}
        onClose={() => { setOpen(false); setEdit(null); }}
        width="max-w-6xl"
        footer={<>
          {tab === 'purchase' && (
            <button className="mr-auto text-cyan-700 border-cyan-300" style={{ padding: '4px 12px', border: '1px solid #67e8f9', borderRadius: '6px', fontSize: '13px' }}
              onClick={() => setImportOpen(true)}>📋 表格导入入库材料</button>
          )}
          <button className={C.button.ghost} onClick={() => { setOpen(false); setEdit(null); }}>取消</button>
          <button className={C.button.ghost} onClick={() => saveEditing(false)}>保存草稿</button>
          <button className={C.button.success} onClick={() => saveEditing(true)}>提交并审核入库</button>
        </>}
      >
        {edit && (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 mb-4">
              <div><label className={C.label}>单号</label><Input value={edit.code} onChange={() => {}} className="bg-slate-50" /></div>
              <div><label className={C.label}>日期</label><Input type="date" value={edit.docDate} onChange={v => setField('docDate', v)} /></div>
              <div>
                <label className={C.label + ' after:content-["*"] after:ml-0.5 after:text-rose-500'}>入库组织</label>
                <Select value={edit.orgId} onChange={onOrgChanged}
                  options={orgs.map(o => ({ value: o.id, label: o.path }))} placeholder="选择组织" />
              </div>
              <div>
                <label className={C.label + ' after:content-["*"] after:ml-0.5 after:text-rose-500'}>入库仓库</label>
                <Select value={edit.warehouseId || ''} onChange={v => setField('warehouseId', v)}
                  options={warehouses.map(w => ({ value: w.id, label: w.name + (w.keeper ? `(${w.keeper})` : '') }))}
                  placeholder={edit.orgId ? '选择仓库' : '请先选组织'} />
              </div>
            </div>

            {/* 类型专属区 */}
            {tab === 'purchase' && (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 mb-4 p-3 bg-cyan-50/40 rounded-xl border border-cyan-100">
                <div>
                  <label className={C.label + ' after:content-["*"] after:ml-0.5 after:text-rose-500'}>采购来源</label>
                  <div className="flex gap-2">
                    {(['contract', 'retail'] as const).map(src => (
                      <label key={src} className={`flex-1 flex items-center gap-1.5 px-3 py-2 rounded-md border cursor-pointer text-sm ${edit.purchaseSource === src ? 'border-cyan-500 bg-white text-cyan-700 font-medium shadow-sm' : 'border-slate-200 bg-white text-slate-600'}`}>
                        <input type="radio" checked={edit.purchaseSource === src}
                          onChange={() => onSourceChanged(src)} className="accent-cyan-600" />
                        {src === 'contract' ? '材料合同' : '零星采购'}
                      </label>
                    ))}
                  </div>
                </div>
                <div>
                  <label className={C.label}>关联材料合同（系统同步）</label>
                  <Select value={edit.contractId || ''} onChange={onContractChanged}
                    options={contracts.map(c => ({ value: c.id, label: `${c.code} ${c.name}` }))}
                    placeholder={edit.purchaseSource === 'contract' ? '从合同系统选择材料合同' : '零星采购无需选择'}
                    className={edit.purchaseSource !== 'contract' ? 'opacity-50 cursor-not-allowed' : ''}
                  />
                </div>
                <div>
                  <label className={C.label}>购买方（甲方）</label>
                  <Input value={edit.buyer || ''} onChange={v => setField('buyer', v)}
                    className={edit.purchaseSource === 'contract' && edit.contractId ? 'bg-slate-50 text-cyan-800' : ''} />
                </div>
                <div>
                  <label className={C.label}>供应商（乙方）</label>
                  <Input value={edit.supplier || ''} onChange={v => setField('supplier', v)}
                    className={edit.purchaseSource === 'contract' && edit.contractId ? 'bg-slate-50 text-cyan-800' : ''} />
                </div>
                <div>
                  <label className={C.label}>定项（关联项目 / 专项专用）</label>
                  <Select value={edit.projectId || ''} onChange={onProjectChanged}
                    options={projects.map(p => ({ value: p.id, label: `${p.name}（${p.org || ''}）` }))}
                    placeholder="选择后，本次入库材料只供该项目使用（定项）" />
                </div>
                <div>
                  <label className={C.label}>经办人</label>
                  <Input value={edit.handler || ''} onChange={v => setField('handler', v)} />
                </div>
                <div className="lg:col-span-2">
                  <label className={C.label}>备注</label>
                  <Input value={edit.remark || ''} onChange={v => setField('remark', v)}
                    placeholder="采购批次、验收情况、运输单据号等" />
                </div>
              </div>
            )}

            {tab === 'return' && (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 mb-4 p-3 bg-emerald-50/40 rounded-xl border border-emerald-100">
                <div className="lg:col-span-2">
                  <label className={C.label + ' after:content-["*"] after:ml-0.5 after:text-rose-500'}>关联领料单（选择后自动带出可退数量）</label>
                  <Select value={edit.issueOrderId || ''} onChange={bindIssueOrder}
                    options={getIssueOrders()
                      .filter(i => (i.status === 'issuing' || i.status === 'completed') && i.lines.some(l => l.issuedQty - l.returnedQty > 0))
                      .map(i => ({ value: i.id, label: `${i.code} ${i.projectName}/${i.teamName}（可退）` }))}
                    placeholder="选择领料单（系统会带出该领料单已发未退的材料数量）" />
                </div>
                <div>
                  <label className={C.label}>所属项目</label>
                  <Input value={edit.projectName || ''} onChange={() => {}} className="bg-slate-50" />
                </div>
                <div>
                  <label className={C.label}>领料单号</label>
                  <Input value={edit.issueOrderCode || ''} onChange={() => {}} className="bg-slate-50" />
                </div>
                <div>
                  <label className={C.label}>经办人</label>
                  <Input value={edit.handler || ''} onChange={v => setField('handler', v)} />
                </div>
                <div className="md:col-span-3">
                  <label className={C.label}>备注</label>
                  <Input value={edit.remark || ''} onChange={v => setField('remark', v)} placeholder="退料原因：规格不符/用量节约/现场退回等" />
                </div>
              </div>
            )}

            {tab === 'transfer' && (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 mb-4 p-3 bg-amber-50/40 rounded-xl border border-amber-100">
                <div className="lg:col-span-2">
                  <label className={C.label + ' after:content-["*"] after:ml-0.5 after:text-rose-500'}>关联调拨单（对方组织调出到本组织，选择后自动带出）</label>
                  <Select value={edit.transferOrderId || ''} onChange={bindTransferOrder}
                    options={getTransferOrders()
                      .filter(t => (t.status === 'out_done' || t.status === 'completed'))
                      .map(t => ({ value: t.id, label: `${t.code} ${t.fromOrgName}→${t.toOrgName}` }))}
                    placeholder="选择调拨单（必须是对方组织已出库，当前组织是调入组织）" />
                </div>
                <div>
                  <label className={C.label}>调出组织</label>
                  <Input value={edit.fromOrgName || ''} onChange={() => {}} className="bg-slate-50" />
                </div>
                <div>
                  <label className={C.label}>调拨单号</label>
                  <Input value={edit.transferOrderCode || ''} onChange={() => {}} className="bg-slate-50" />
                </div>
                <div>
                  <label className={C.label}>经办人</label>
                  <Input value={edit.handler || ''} onChange={v => setField('handler', v)} />
                </div>
                <div className="md:col-span-3">
                  <label className={C.label}>备注</label>
                  <Input value={edit.remark || ''} onChange={v => setField('remark', v)} />
                </div>
              </div>
            )}

            {tab === 'other' && (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 mb-4 p-3 bg-slate-50 rounded-xl border border-slate-200">
                <div>
                  <label className={C.label}>经办人</label>
                  <Input value={edit.handler || ''} onChange={v => setField('handler', v)} />
                </div>
                <div className="md:col-span-2 lg:col-span-3">
                  <label className={C.label}>备注（入库原因）</label>
                  <Input value={edit.remark || ''} onChange={v => setField('remark', v)} placeholder="盘盈、捐赠、归还等..." />
                </div>
              </div>
            )}

            <DocLineEditor
              lines={edit.lines}
              onChange={setLines}
              onPickMaterials={() => setPickOpen(true)}
            />
          </>
        )}
      </Modal>
      <MaterialPicker open={pickOpen} onClose={() => setPickOpen(false)} onPick={onPickMats} />
      <ImportLinesModal open={importOpen} onClose={() => setImportOpen(false)} onConfirm={onImportRows} />

      {/* 查看 */}
      <Modal title={`入库单 ${current?.code || ''}`} open={!!current} onClose={() => setViewId(null)} width="max-w-5xl"
        footer={<>
          <button className={C.button.ghost} onClick={() => setViewId(null)}>关闭</button>
          {current?.status === 'draft' && (
            <button className={C.button.success} onClick={() => { auditStockIn(current.id); refresh(); setViewId(null); toast('已审核入库，库存已更新', 'success'); }}>
              审核入库
            </button>
          )}
        </>}>
        {current && (
          <>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4 text-sm">
              {[
                ['单据编号', current.code],
                ['入库类型', STOCK_IN_TYPE_MAP[current.type]],
                ['组织', current.orgName],
                ['日期', current.docDate],
                ['状态', STOCK_IN_STATUS_MAP[current.status]],
                ['定项(项目)', current.projectName || '-'],
                ['金额(含税)', `¥ ${(current.totalAmount || 0).toFixed(2)}`],
                ['经办人', current.handler || '-'],
              ].map(([k, v]) => (
                <div key={k} className="bg-slate-50 rounded-lg px-3 py-2">
                  <div className="text-[11px] text-slate-500 mb-0.5">{k}</div>
                  <div className="text-slate-800 font-medium truncate">{v}</div>
                </div>
              ))}
            </div>
            {current.type === 'purchase' && (
              <div className="bg-cyan-50/40 rounded-xl border border-cyan-100 p-3 mb-4 grid grid-cols-1 md:grid-cols-3 gap-3 text-sm">
                <div><div className="text-[11px] text-cyan-700 mb-0.5">采购来源</div>{current.purchaseSource === 'contract' ? '材料合同' : '零星采购'}</div>
                <div><div className="text-[11px] text-cyan-700 mb-0.5">合同 / 编码</div>{current.contractName} <span className="text-slate-400">{current.contractCode}</span></div>
                <div><div className="text-[11px] text-cyan-700 mb-0.5">甲乙双方</div>甲方: {current.buyer || '-'}<br />乙方: {current.supplier || '-'}</div>
              </div>
            )}
            {current.type === 'return' && (
              <div className="bg-emerald-50/40 rounded-xl border border-emerald-100 p-3 mb-4 text-sm">
                关联领料单：<b>{current.issueOrderCode || '-'}</b>
                {current.autoGenerated && <span className="ml-2 text-[11px] bg-emerald-100 text-emerald-800 px-2 py-0.5 rounded-full">领料单直接退料自动生成</span>}
              </div>
            )}
            {current.type === 'transfer' && (
              <div className="bg-amber-50/40 rounded-xl border border-amber-100 p-3 mb-4 text-sm">
                关联调拨单：<b>{current.transferOrderCode || '-'}</b>，调出：{current.fromOrgName || '-'}
                {current.autoGenerated && <span className="ml-2 text-[11px] bg-amber-100 text-amber-800 px-2 py-0.5 rounded-full">调拨单入库自动生成</span>}
              </div>
            )}
            <DocLineEditor readOnly lines={current.lines} onChange={() => {}} onPickMaterials={() => {}} />
            {current.remark && <div className="mt-3 text-sm text-slate-500">备注：{current.remark}</div>}
          </>
        )}
      </Modal>
    </div>
  );
}
