/**
 * 材料出库管理（领料出库 / 调拨出库 / 其他出库）
 * 前两类通常是领料单/调拨单联动自动生成的，在列表上审核后扣减库存。
 * 其他出库可主动新建（用于直接出库场景，非领料/调拨）。
 */

import React, { useMemo, useState } from 'react';
import type { Project, Team } from '@/types';
import type { StockOutOrder, StockOutType, DocLineItem, Material } from './types';
import {
  C, Modal, SearchBar, Input, Select, StatusPill, TypePill,
  MaterialPicker, DocLineEditor, materialsToLines, useToast,
} from './_shared';
import {
  getStockOutOrders, upsertStockOut, auditStockOut, nextDocCode, todayStr, nowStr,
  genId, getOrgsForDropdown, getWarehousesByOrg,
  STOCK_OUT_STATUS_MAP, STOCK_OUT_TYPE_MAP,
  getIssueOrders, getTransferOrders,
} from './materialStore';

interface Props {
  key?: string | number;
  projects: Project[];
  teams: Team[];
  onRefresh?: () => void;
  /** 固定出库类型（从三级菜单进入时锁定，隐藏 Tab 栏） */
  fixedType?: StockOutType;
}

const TABS: { key: StockOutType; label: string; tone: 'cyan' | 'amber' | 'slate' | 'rose' }[] = [
  { key: 'return',   label: '退货出库', tone: 'rose' },
  { key: 'issue',    label: '领料出库', tone: 'cyan' },
  { key: 'transfer', label: '调拨出库', tone: 'amber' },
  { key: 'other',    label: '其他出库', tone: 'slate' },
];

export default function StockOutManager({ projects, teams, onRefresh, fixedType }: Props) {
  const [tab, setTab] = useState<StockOutType>(fixedType || 'issue');
  const [list, setList] = useState<StockOutOrder[]>(() => getStockOutOrders());
  const refresh = () => { setList(getStockOutOrders()); onRefresh?.(); };
  const toast = useToast();
  const orgs = useMemo(() => getOrgsForDropdown().filter(o => o.level === 'project'), []);
  const [kw, setKw] = useState('');
  const [st, setSt] = useState('');

  const [open, setOpen] = useState(false);
  const [edit, setEdit] = useState<StockOutOrder | null>(null);
  const [pickOpen, setPickOpen] = useState(false);
  const [viewId, setViewId] = useState<string | null>(null);

  const filtered = useMemo(() => {
    let r = list.filter(o => o.type === tab);
    if (st) r = r.filter(o => o.status === st);
    if (kw.trim()) {
      const k = kw.trim().toLowerCase();
      r = r.filter(o =>
        o.code.toLowerCase().includes(k) ||
        (o.projectName || '').toLowerCase().includes(k) ||
        (o.teamName || '').toLowerCase().includes(k) ||
        (o.toOrgName || '').toLowerCase().includes(k)
      );
    }
    return r.sort((a, b) => (b.createdAt || '').localeCompare(a.createdAt || ''));
  }, [list, tab, st, kw]);

  const openNew = () => {
    // other 和 return 允许主动新建
    if (tab === 'issue') { toast('领料出库由领料单发料操作自动生成', 'info'); return; }
    if (tab === 'transfer') { toast('调拨出库由调拨单流程自动生成', 'info'); return; }
    const prefix = tab === 'return' ? 'CK-RT-' : 'CK-QT-';
    const doc: StockOutOrder = {
      id: genId('so'), code: nextDocCode(prefix),
      type: tab, orgId: '', orgName: '',
      docDate: todayStr(), status: 'draft', lines: [],
      createdAt: nowStr(), updatedAt: nowStr(),
      autoGenerated: false, sourceModule: 'stock',
    };
    setEdit(doc); setOpen(true);
  };

  const setField = <K extends keyof StockOutOrder>(k: K, v: StockOutOrder[K]) =>
    setEdit(e => e ? { ...e, [k]: v } : e);

  const onPickMats = (mats: Material[]) => {
    if (!edit) return;
    const exist = new Set(edit.lines.map(l => l.materialId));
    setEdit({ ...edit, lines: [...edit.lines, ...materialsToLines(mats.filter(m => !exist.has(m.id)))] });
  };

  const warehouses = edit?.orgId ? getWarehousesByOrg(edit.orgId) : [];

  const saveEditing = (audit: boolean) => {
    if (!edit) return;
    if (!edit.orgId) return toast('请选择出库组织', 'error');
    if (!edit.warehouseId) return toast('请选择出库仓库', 'error');
    if (edit.lines.length === 0) return toast('请添加出库明细', 'error');
    const saved = upsertStockOut({ ...edit, status: audit ? 'submitted' : 'draft' });
    if (audit) auditStockOut(saved.id);
    toast(audit ? '已审核出库，库存已扣减' : '已保存草稿', 'success');
    setOpen(false); setEdit(null); refresh();
  };

  const current = viewId ? list.find(l => l.id === viewId) : null;

  return (
    <div className="p-5">
      {!fixedType && (
      <div className="flex items-center gap-2 mb-4">
        {TABS.map(t => {
          const count = list.filter(o => o.type === t.key).length;
          const active = tab === t.key;
          return (
            <button key={t.key} onClick={() => setTab(t.key)}
              className={`flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm font-medium transition-all ${
                active
                  ? 'bg-white border-cyan-400 text-cyan-700 shadow-sm ring-2 ring-cyan-100'
                  : 'bg-white/50 border-slate-200 text-slate-600 hover:bg-white hover:border-slate-300'
              }`}>
              {t.label}
              <span className={`px-1.5 py-0.5 rounded-md text-[11px] ${active ? 'bg-cyan-100 text-cyan-700' : 'bg-slate-100 text-slate-500'}`}>{count}</span>
            </button>
          );
        })}
      </div>
      )}

      <SearchBar onAdd={(tab === 'other' || tab === 'return') ? openNew : undefined} addLabel={`+ 新建${STOCK_OUT_TYPE_MAP[tab]}`}>
        <Input value={kw} onChange={setKw} placeholder={`搜索${STOCK_OUT_TYPE_MAP[tab]}单号/项目/班组/调入组织`} className="!w-72" />
        <Select value={st} onChange={setSt}
          options={Object.keys(STOCK_OUT_STATUS_MAP).map(k => ({ value: k, label: STOCK_OUT_STATUS_MAP[k] }))}
          placeholder="状态" className="!w-40" />
        <button className={C.button.ghost} onClick={refresh}>刷新</button>
      </SearchBar>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        <table className={C.table}>
          <thead>
            <tr>
              <th className={C.th}>单据编号</th>
              <th className={C.th}>类型</th>
              <th className={C.th}>出库组织</th>
              <th className={C.th}>去向</th>
              {tab === 'issue' && <th className={C.th}>项目 / 班组</th>}
              {tab === 'transfer' && <th className={C.th}>调入组织</th>}
              {tab === 'issue' && <th className={C.th}>关联领料单</th>}
              {tab === 'transfer' && <th className={C.th}>关联调拨单</th>}
              <th className={`${C.th} text-right`}>金额</th>
              <th className={C.th}>日期</th>
              <th className={C.th}>状态</th>
              <th className={C.th}>操作</th>
            </tr>
          </thead>
          <tbody>
            {filtered.length === 0 && (
              <tr><td colSpan={12} className={`${C.td} text-center text-slate-400 py-10`}>
                暂无{STOCK_OUT_TYPE_MAP[tab]}单据
                {tab === 'issue' && <div className="text-[11px] mt-1">在领料单里点击"发料出库"后，会自动在此生成领料出库单</div>}
                {tab === 'transfer' && <div className="text-[11px] mt-1">在调拨单里执行"调出方出库"后，会自动在此生成调拨出库单</div>}
                {tab === 'valuation' && <div className="text-[11px] mt-1">在"库存转移(价拨)"模块提交后，会自动生成价拨出库单</div>}
                {tab === 'other' && <div className="text-[11px] mt-1">点击右上角"+ 新建其他出库"主动创建</div>}
              </td></tr>
            )}
            {filtered.map(o => (
              <tr key={o.id} className="hover:bg-slate-50">
                <td className={`${C.td} font-medium`}>
                  {o.code}
                  {o.autoGenerated && <span className="ml-1 text-[10px] text-slate-400">（自动）</span>}
                </td>
                <td className={C.td}><TypePill text={STOCK_OUT_TYPE_MAP[o.type]} tone={TABS.find(t => t.key === o.type)?.tone} /></td>
                <td className={C.td}>{o.orgName}</td>
                <td className={C.td}>
                  {o.type === 'issue' && o.teamName ? <span className="text-slate-700">班组：{o.teamName}</span> : null}
                  {o.type === 'transfer' && o.toOrgName ? <span className="text-amber-700">调往：{o.toOrgName}</span> : null}
                  {o.type === 'valuation' && (
                    <TypePill text={o.valuationMode === 'external' ? '外部价拨' : '内部转移'} tone="rose" />
                  )}
                  {o.type === 'other' && <span className="text-slate-400">-</span>}
                </td>
                {tab === 'issue' && (
                  <td className={C.td}>
                    <div className="text-slate-800 font-medium">{o.projectName}</div>
                    <div className="text-[11px] text-slate-500">{o.teamName}</div>
                  </td>
                )}
                {tab === 'transfer' && <td className={C.td + ' text-amber-700 font-medium'}>{o.toOrgName || '-'}</td>}
                {tab === 'issue' && <td className={C.td}>{o.issueOrderCode || '-'}</td>}
                {tab === 'transfer' && <td className={C.td}>{o.transferOrderCode || '-'}</td>}
                <td className={`${C.td} text-right tabular-nums text-cyan-700 font-medium`}>¥ {(o.totalAmount || 0).toFixed(2)}</td>
                <td className={C.td}>{o.docDate}</td>
                <td className={C.td}><StatusPill status={STOCK_OUT_STATUS_MAP[o.status]} /></td>
                <td className={`${C.td} whitespace-nowrap space-x-1`}>
                  <button className={C.button.tiny} onClick={() => setViewId(o.id)}>查看</button>
                  {o.status === 'draft' && (o.type === 'other' || !o.autoGenerated) && (
                    <button className={C.button.tiny + ' text-cyan-700 border-cyan-300'}
                      onClick={() => { setEdit(o); setOpen(true); }}>编辑</button>
                  )}
                  {o.status === 'draft' && (
                    <button className={C.button.tiny + ' text-emerald-700 border-emerald-300'}
                      onClick={() => {
                        const r = auditStockOut(o.id);
                        if (!r) return toast('库存不足，无法出库', 'error');
                        refresh();
                        toast('已审核出库，库存已扣减', 'success');
                      }}>审核出库</button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* 新建/编辑（仅其他出库） */}
      <Modal title={`其他出库 - ${edit?.code || ''}`} open={open} onClose={() => { setOpen(false); setEdit(null); }}
        width="max-w-5xl"
        footer={<>
          <button className={C.button.ghost} onClick={() => { setOpen(false); setEdit(null); }}>取消</button>
          <button className={C.button.ghost} onClick={() => saveEditing(false)}>保存草稿</button>
          <button className={C.button.success} onClick={() => saveEditing(true)}>提交并审核出库</button>
        </>}>
        {edit && (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 mb-4">
              <div><label className={C.label}>单号</label><Input value={edit.code} onChange={() => {}} className="bg-slate-50" /></div>
              <div><label className={C.label}>日期</label><Input type="date" value={edit.docDate} onChange={v => setField('docDate', v)} /></div>
              <div>
                <label className={C.label + ' after:content-["*"] after:ml-0.5 after:text-rose-500'}>出库组织</label>
                <Select value={edit.orgId} onChange={v => {
                  const o = orgs.find(o => o.id === v);
                  setEdit(e => e ? { ...e, orgId: v, orgName: o?.name || '', warehouseId: undefined } : e);
                }} options={orgs.map(o => ({ value: o.id, label: o.path }))} placeholder="选择组织" />
              </div>
              <div>
                <label className={C.label + ' after:content-["*"] after:ml-0.5 after:text-rose-500'}>出库仓库</label>
                <Select value={edit.warehouseId || ''} onChange={v => setField('warehouseId', v)}
                  options={warehouses.map(w => ({ value: w.id, label: w.name + (w.keeper ? `（${w.keeper}）` : '') }))}
                  placeholder={edit.orgId ? '选择仓库' : '请先选组织'} />
              </div>
              <div>
                <label className={C.label}>定项（项目）</label>
                <Select value={edit.projectId || ''} onChange={v => {
                  const p = projects.find(p => p.id === v);
                  setEdit(e => e ? { ...e, projectId: v, projectName: p?.name } : e);
                }} options={projects.map(p => ({ value: p.id, label: p.name }))} placeholder="可选" />
              </div>
              <div>
                <label className={C.label}>经办人</label>
                <Input value={edit.handler || ''} onChange={v => setField('handler', v)} />
              </div>
              <div className="md:col-span-2">
                <label className={C.label}>备注（出库原因）</label>
                <Input value={edit.remark || ''} onChange={v => setField('remark', v)} placeholder="报损/样品/调账等..." />
              </div>
            </div>
            <DocLineEditor
              lines={edit.lines}
              onChange={(l) => setEdit({ ...edit, lines: l })}
              onPickMaterials={() => setPickOpen(true)}
            />
          </>
        )}
      </Modal>
      <MaterialPicker open={pickOpen} onClose={() => setPickOpen(false)} onPick={onPickMats} />

      {/* 查看 */}
      <Modal title={`出库单 ${current?.code || ''}`} open={!!current} onClose={() => setViewId(null)} width="max-w-5xl"
        footer={<>
          <button className={C.button.ghost} onClick={() => setViewId(null)}>关闭</button>
          {current?.status === 'draft' && (
            <button className={C.button.success} onClick={() => {
              const r = auditStockOut(current.id);
              if (!r) return toast('库存不足', 'error');
              refresh(); setViewId(null); toast('已审核出库', 'success');
            }}>审核出库</button>
          )}
        </>}>
        {current && (
          <>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4 text-sm">
              {[
                ['单号', current.code],
                ['类型', STOCK_OUT_TYPE_MAP[current.type]],
                ['出库组织', current.orgName],
                ['日期', current.docDate],
                ['状态', STOCK_OUT_STATUS_MAP[current.status]],
                ['项目', current.projectName || '-'],
                ['金额(含税)', `¥ ${(current.totalAmount || 0).toFixed(2)}`],
                ['经办人', current.handler || '-'],
              ].map(([k, v]) => (
                <div key={k} className="bg-slate-50 rounded-lg px-3 py-2">
                  <div className="text-[11px] text-slate-500 mb-0.5">{k}</div>
                  <div className="text-slate-800 font-medium truncate">{v}</div>
                </div>
              ))}
            </div>
            {current.type === 'issue' && (
              <div className="bg-cyan-50/40 rounded-xl border border-cyan-100 p-3 mb-4 grid grid-cols-3 gap-3 text-sm">
                <InfoCard title="关联领料单" value={current.issueOrderCode || '-'} />
                <InfoCard title="班组(定组)" value={current.teamName || '-'} />
                <InfoCard title="项目(定项)" value={current.projectName || '-'} />
              </div>
            )}
            {current.type === 'transfer' && (
              <div className="bg-amber-50/40 rounded-xl border border-amber-100 p-3 mb-4 grid grid-cols-3 gap-3 text-sm">
                <InfoCard title="关联调拨单" value={current.transferOrderCode || '-'} />
                <InfoCard title="调入组织" value={current.toOrgName || '-'} />
                <InfoCard title="来源" value={current.autoGenerated ? '调拨单自动生成' : '手动'} />
              </div>
            )}
            <DocLineEditor readOnly lines={current.lines} onChange={() => {}} onPickMaterials={() => {}} />
            {current.remark && <div className="mt-3 text-sm text-slate-500">备注：{current.remark}</div>}
          </>
        )}
      </Modal>
    </div>
  );
}

function InfoCard({ title, value }: { title: string; value: string }) {
  return (
    <div>
      <div className="text-[11px] text-slate-500 mb-0.5">{title}</div>
      <div className="font-medium text-slate-800">{value}</div>
    </div>
  );
}
