/**
 * 材料系统 - 类型定义
 * 涵盖：材料编码体系、入库/出库单据、领料单、调拨单、库存(含库存转移)
 */

// =============== 基础数据 ===============

/** 材料主数据（编码体系） */
export interface Material {
  id: string;
  code: string;             // 材料编码（唯一）
  name: string;             // 材料名称
  category: string;         // 分类（如：沥青材料、水泥材料、砂石料、钢材、劳保、五金…）
  spec?: string;            // 规格型号
  unit: string;             // 计量单位（吨、公斤、米、个、箱…）
  price?: number;           // 默认参考单价（含税元）
  taxRate?: number;         // 税率，默认 0.13
  remark?: string;
  createdAt: string;
  updatedAt: string;
}

// =============== 业务单据通用 ===============

/** 单据明细行 */
export interface DocLineItem {
  id: string;                // 行ID
  materialId: string;        // 材料ID
  materialCode: string;      // 冗余：材料编码
  materialName: string;      // 冗余：材料名称
  spec?: string;
  unit: string;
  quantity: number;          // 数量（入库为正，出库为正；方向由单据 type 决定）
  unitPrice?: number;        // 不含税单价
  amount?: number;           // 不含税金额（自动计算）
  taxAmount?: number;        // 税额
  totalAmount?: number;      // 价税合计
  remark?: string;
  // 调拨/退料场景用：引用源头单据行
  sourceLineId?: string;
}

/** 单据行（限额领料 - 预算/定额） */
export interface QuotaLineItem extends DocLineItem {
  issuedQty: number;         // 已发数量（累计出库）
  returnedQty: number;       // 已退数量
  quotaQty: number;          // 定额/限额数量
}

// =============== 入库 ===============

export type StockInType = 'purchase' | 'return' | 'transfer' | 'other';
export type PurchaseSource = 'contract' | 'retail';

/** 入库单 */
export interface StockInOrder {
  id: string;
  code: string;                       // 单据编号
  type: StockInType;                  // 入库类型
  orgId: string;                      // 入库组织
  orgName: string;                    // 冗余
  warehouseId?: string;               // 仓库
  projectId?: string;                 // 定项：关联项目（专项专用）
  projectName?: string;
  // 采购入库字段
  purchaseSource?: PurchaseSource;    // 采购来源
  contractId?: string;                // 合同
  contractCode?: string;
  contractName?: string;
  buyer?: string;                     // 购买方（甲方）
  supplier?: string;                  // 供应商（乙方）
  // 退料入库字段
  issueOrderId?: string;              // 关联领料单
  issueOrderCode?: string;
  // 调拨入库字段
  transferOrderId?: string;           // 关联调拨单
  transferOrderCode?: string;
  transferOutId?: string;             // 对方调拨出库单
  fromOrgId?: string;                 // 调出组织
  fromOrgName?: string;
  // 其他
  handler?: string;                   // 经办人
  docDate: string;                    // 单据日期
  status: 'draft' | 'submitted' | 'audited' | 'voided';
  totalAmount?: number;               // 价税合计
  remark?: string;
  lines: DocLineItem[];
  createdAt: string;
  updatedAt: string;
  // 自动标记：非主动创建来源（true = 领料单/调拨单联动自动生成）
  autoGenerated?: boolean;
  sourceModule?: 'issue' | 'transfer' | 'stock' | 'valuation';
}

// =============== 出库 ===============

export type StockOutType = 'issue' | 'transfer' | 'other' | 'valuation' | 'return';

/** 出库单 */
export interface StockOutOrder {
  id: string;
  code: string;
  type: StockOutType;                 // 领料出库 / 调拨出库 / 其他出库 / 价拨出库(库存转移)
  orgId: string;
  orgName: string;
  warehouseId?: string;
  projectId?: string;
  projectName?: string;
  // 领料出库
  issueOrderId?: string;              // 关联领料单
  issueOrderCode?: string;
  teamId?: string;                    // 领料班组
  teamName?: string;
  // 调拨出库
  transferOrderId?: string;
  transferOrderCode?: string;
  toOrgId?: string;                   // 调入组织
  toOrgName?: string;
  // 价拨/库存转移
  valuationMode?: 'internal' | 'external'; // 内部转移/外部价拨
  // 其他
  handler?: string;
  docDate: string;
  status: 'draft' | 'submitted' | 'audited' | 'voided';
  totalAmount?: number;
  remark?: string;
  lines: DocLineItem[];
  createdAt: string;
  updatedAt: string;
  autoGenerated?: boolean;
  sourceModule?: 'issue' | 'transfer' | 'valuation' | 'stock';
}

// =============== 领料单（核心业务单据）===============

export type IssueOrderStatus = 'draft' | 'submitted' | 'issuing' | 'completed' | 'closed' | 'voided';

/** 领料单 — 定项定组（限额领料） */
export interface IssueOrder {
  id: string;
  code: string;
  orgId: string;                      // 发起组织
  orgName: string;
  projectId: string;                  // 定项：项目（必填，专项专用）
  projectName: string;
  teamId: string;                     // 定组：领料班组
  teamName: string;
  purpose?: string;                   // 用途/作业部位（保留字段兼容旧数据，新表单不再录入）
  handler?: string;                   // 领料人
  operator?: string;                  // 操作人（当前登录用户，默认）
  docDate: string;
  status: IssueOrderStatus;
  remark?: string;
  lines: QuotaLineItem[];             // 带定额+已发/已退
  createdAt: string;
  updatedAt: string;
}

// =============== 调拨单（核心业务单据 - 跨组织+简单流程）===============

/** 调拨单状态：
 *  draft - 草稿
 *  submitted - 调出方提交（待调入方确认）
 *  confirmed - 调入方确认（调出方可出库，待调入方入库）
 *  out_done - 调出方已出库
 *  completed - 调入方已入库，全部完成
 *  rejected - 调入方驳回
 *  voided - 作废
 */
export type TransferOrderStatus = 'draft' | 'submitted' | 'confirmed' | 'out_done' | 'completed' | 'rejected' | 'voided';

export interface TransferOrder {
  id: string;
  code: string;
  fromOrgId: string;                  // 调出组织
  fromOrgName: string;
  toOrgId: string;                    // 调入组织
  toOrgName: string;
  reason?: string;                    // 调拨原因
  docDate: string;
  status: TransferOrderStatus;
  remark?: string;
  rejectReason?: string;
  // 流程动作时间戳/人
  submitBy?: string;
  submitAt?: string;
  confirmBy?: string;
  confirmAt?: string;
  rejectBy?: string;
  rejectAt?: string;
  outBy?: string;
  outAt?: string;
  inBy?: string;
  inAt?: string;
  // 生成的出/入库单ID
  outOrderId?: string;
  inOrderId?: string;
  lines: DocLineItem[];
  totalAmount?: number;                 // 价税合计（recalcDocTotals 计算）
  createdAt: string;
  updatedAt: string;
}

// =============== 库存 ===============

/** 实时库存（按组织+仓库+材料 聚合） */
export interface StockBalance {
  id: string;                           // orgId|warehouseId|materialId
  orgId: string;
  orgName: string;
  warehouseId: string;
  warehouseName: string;
  materialId: string;
  materialCode: string;
  materialName: string;
  spec?: string;
  unit: string;
  qty: number;                          // 数量
  avgCost: number;                      // 加权平均成本（不含税）
  amount: number;                       // 库存金额
  lastMoveDate: string;                 // 最后变动日期
}

/** 库存转移（价拨）单 — 组织内/外部价拨 */
export type ValuationOrderStatus = 'draft' | 'submitted' | 'done' | 'voided';
export interface ValuationOrder {
  id: string;
  code: string;
  orgId: string;
  orgName: string;
  mode: 'internal' | 'external';        // 内部转移(仓库间) / 外部价拨
  fromWarehouseId?: string;
  fromWarehouseName?: string;
  toWarehouseId?: string;
  toWarehouseName?: string;
  externalParty?: string;               // 外部价拨：对方单位
  priceMode: 'cost' | 'custom';         // 成本价 / 自定义价
  docDate: string;
  status: ValuationOrderStatus;
  remark?: string;
  outOrderId?: string;                  // 生成的出库单
  inOrderId?: string;                   // 内部转移时对应的入库单
  lines: DocLineItem[];
  totalAmount?: number;                 // 价税合计（recalcDocTotals 计算）
  createdAt: string;
  updatedAt: string;
}

// =============== 仓库（简化）===============
export interface Warehouse {
  id: string;
  name: string;
  orgId: string;
  address?: string;
  keeper?: string;
  enabled: boolean;
}

// =============== 材料管理中心菜单 ===============
export type MaterialAdminTab =
  | 'issue'           // 领料单
  | 'transfer'        // 调拨单
  | 'stockIn'         // 入库
  | 'stockOut'        // 出库
  | 'valuation'       // 库存转移（价拨）
  | 'balance'         // 库存查询
  | 'master';         // 材料编码/仓库基础数据
