import { MainLine, Team, Project, ProjectChange, Contract, ContractOperation } from './types';

export const MOCK_MAIN_LINES: MainLine[] = [
  {
    id: '1',
    code: 'B10412',
    name: '路线全称',
    abbr: '路线简称',
    startStake: 'K01+001',
    endStake: 'K02+101',
    direction: '上行',
    length: 12.31,
    remark: '这里是备注',
  },
  {
    id: '2',
    code: 'B10412',
    name: '路线名称',
    abbr: '路线简称',
    startStake: 'K01+001',
    endStake: 'K02-101',
    direction: '下行',
    length: 3.12,
    remark: '这里是备注',
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: '1',
    name: '中分带班组',
    leader: '张三',
    phone: '13800138000',
    type: '自有',
    status: '在场',
    members: [
      { id: 'm1', name: '普工', role: '普工', idCard: '320102********1212', age: 42, gender: '男', status: '在岗', joinDate: '2026-03-25', phone: '13811111111' },
    ],
  },
  {
    id: '2',
    name: '小修班组',
    leader: '李四',
    phone: '13800138001',
    type: '分包',
    status: '在场',
    members: [],
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: '永蓝边坡应急',
    code: 'RCYH-001',
    abbr: '永蓝边坡',
    type: '高速其他专项',
    status: '已立项',
    dept: '项目部一',
    org: '沪杭甬养护**项目部',
    startDate: '2025/05/10',
    endDate: '2025/11/20',
    creator: '张三',
    createDate: '2026-03-02',
    contractSigned: true,
    projectCode: 'YH20220228',
    undertakeMethod: '直营',
    qualification: '公路养护甲级',
    nature: '专项工程',
    completionType: '养护工程',
    maintenanceArea: '沪杭甬',
    maintenanceScope: 'K0+000-K100+000',
    property: ['经营性'],
    summary: '本项目主要负责永蓝高速边坡应急抢修工程，包括边坡加固、排水系统清理等。',
    mainLines: ['1', '2'],
    teams: [],
    contractId: 'c1',
  },
  {
    id: '2',
    name: '药湖桥下整治',
    code: 'RCYH-002',
    abbr: '药湖桥下',
    type: '高速其他专项',
    status: '已立项',
    dept: '项目部一',
    org: '沪杭甬养护**项目部',
    startDate: '2022/02/28',
    endDate: '2026/02/28',
    creator: '李四',
    createDate: '2026-03-02',
    contractSigned: false,
    projectCode: 'YH20220229',
    undertakeMethod: '直营',
    qualification: '公路养护甲级',
    nature: '专项工程',
    completionType: '养护工程',
    maintenanceArea: '沪杭甬',
    maintenanceScope: 'K100+000-K200+000',
    property: ['经营性'],
    summary: '本项目主要负责药湖大桥桥下空间整治，包括违章建筑拆除、地面硬化等。',
    mainLines: ['1'],
    teams: [],
  },
];

export const MOCK_CHANGES: ProjectChange[] = [
  {
    id: '1',
    changeNo: 'XMBG-2603001',
    projectId: '1',
    projectName: '永蓝边坡应急',
    projectCode: 'RCYH-001',
    initiator: '沪杭养护',
    initiationTime: '2022/02/28',
    status: '草稿',
    reason: '项目范围调整',
    changeContents: ['基本信息', '路段信息'],
    beforeData: MOCK_PROJECTS[0],
    afterData: { ...MOCK_PROJECTS[0], abbr: '永蓝边坡(变更后)' },
  },
  {
    id: '2',
    changeNo: 'XMBG-2603002',
    projectId: '2',
    projectName: '药湖桥下整治',
    projectCode: 'RCYH-001',
    initiator: '顺桥养护',
    initiationTime: '2022/02/28',
    status: '审批中',
    reason: '增加施工班组',
    changeContents: ['班组信息'],
    beforeData: MOCK_PROJECTS[1],
    afterData: { ...MOCK_PROJECTS[1], teams: ['1', '2'] },
  },
  {
    id: '3',
    changeNo: 'XMBG-2603003',
    projectId: '1',
    projectName: '杭新景日常小修20-22',
    projectCode: 'RCYH-001',
    initiator: '交工养护',
    initiationTime: '2022/02/28',
    status: '已变更',
    reason: '合同主体变更',
    changeContents: ['合同信息'],
    beforeData: MOCK_PROJECTS[0],
    afterData: { ...MOCK_PROJECTS[0], undertakeMethod: '分包' },
  }
];

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'c1',
    name: '这里是合同的名称',
    code: 'JGSC-GCSGHT-2025-001',
    amount: 142412.31,
    financialStatus: '交投已推送',
    agency: '浙江交工_顺畅养护公司_湖州项目部_工程科',
    type: '结算类合同',
    source: '系统同步',
    partyA: '浙江交工集团',
    partyB: '顺畅养护公司',
    status: '已确认', // Make sure they are confirmed to appear in ledger
    transferCount: 0,
    isLocked: false,
    createTime: '2024-03-20 10:00',
    performanceStartDate: '2025-05-10',
    performanceEndDate: '2025-11-20',
  },
  {
    id: 'c2',
    name: '年度营销推广协议',
    code: 'HT20231113003',
    amount: 500000.00,
    financialStatus: '待推送',
    agency: '浙江交工_顺畅养护公司_杭州项目部',
    type: '养护合同',
    source: '系统同步',
    partyA: '浙江交工集团',
    partyB: '顺畅养护公司',
    status: '已确认', // Ensure ledger visibility
    transferCount: 1,
    isLocked: false,
    createTime: '2024-03-19 15:30',
    performanceStartDate: '2024-06-01',
    performanceEndDate: '2026-06-30',
  },
  {
    id: 'c3',
    name: '人力资源外包服务合同',
    code: 'HT20231112004',
    amount: 1200000.00,
    financialStatus: '交投已推送',
    agency: '浙江交工_顺畅养护公司_宁波项目部',
    type: '施工（总）承包',
    source: '协同合同',
    partyA: '浙江交工集团',
    partyB: '顺畅养护公司',
    status: '已确认', // Ensure ledger visibility
    transferCount: 2,
    isLocked: true,
    createTime: '2024-03-18 09:00',
    performanceStartDate: '2023-11-01',
    performanceEndDate: '2027-04-30',
  }
];

export const MOCK_CONTRACT_OPERATIONS: ContractOperation[] = [
  {
    id: 'op1',
    contractId: 'c1',
    contractName: '这里是合同的名称',
    contractCode: 'JGSC-GCSGHT-2025-001',
    type: '退回',
    operator: '张丽',
    time: '2023-11-15 14:30',
    reason: '这个合同不属于本组织核算的，是有另外一个组织核算...'
  },
  {
    id: 'op2',
    contractId: 'c2',
    contractName: '办公设备采购合同',
    contractCode: 'HT20231114002',
    type: '转派',
    operator: '王磊',
    time: '2023-11-14 16:45',
    reason: '合同事务数存在风险点，需...',
    targetOrg: '转派组织名称'
  }
];
